// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("prometheusbeat/fields.yml", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJyMzTEKwzAMheE9p3hbplzAU6+i1C9U1I5dS27J7UtCl0ALXYT44ZMm3LkF1FYy/cZuM8UHwNUTv/RIuzatrmUNA7AoU7R9AyaskhmOeQTAt8qwf3iVFj+t8dG1MQYskown+pTUzzaWPif+QceLa6a55DqeL4j/8u8AAAD//2MvTMo="
}
